#!/bin/bash
set -e
echo "Creating casanode user..."
if id -u casanode &>/dev/null; then
	echo "User 'casanode' already exists."
else
	adduser --system --group --home /opt/casanode --uid 150 casanode
fi

echo "Setting up casanode permissions..."
mkdir -p /opt/casanode/.config/
chown -R casanode:casanode /opt/casanode
if command -v sudo &>/dev/null; then
	usermod -aG sudo,adm,docker casanode
	if ! grep -q "^casanode ALL=(ALL) NOPASSWD:ALL" /etc/sudoers; then
		sed -i '/%sudo\s\+ALL=(ALL:ALL) ALL/a casanode ALL=(ALL) NOPASSWD:ALL' /etc/sudoers
	fi
else
	usermod -aG adm,docker casanode
fi
sed -i "s/<uid>/$(id -u casanode)/g" /etc/casanode.conf
chmod 600 /etc/casanode.conf
chown casanode:casanode /etc/casanode.conf
chmod +x /opt/casanode/startup.sh
chmod +x /opt/casanode/updater.sh

if ! grep -q -- '--experimental' /lib/systemd/system/bluetooth.service; then
	sed -i 's|ExecStart=/usr/libexec/bluetooth/bluetoothd|ExecStart=/usr/libexec/bluetooth/bluetoothd --experimental|' /lib/systemd/system/bluetooth.service
	systemctl daemon-reload
	systemctl restart bluetooth
fi

if ! id -nG casanode | grep -qw bluetooth; then
	usermod -aG bluetooth casanode
fi

echo "Setting correct permissions for /var/log/casanode..."
mkdir -p /var/log/casanode
chown -R casanode:casanode /var/log/casanode
chmod -R 755 /var/log/casanode

echo "Installing node modules..."
npm install --prefix /opt/casanode/app --production || { echo "Error: Failed to install Node.js dependencies."; exit 1; }

echo "Enabling systemd services..."
systemctl enable casanode.service
systemctl enable casanode-ble.service
systemctl enable casanode-startup.service
systemctl daemon-reload

echo "Starting Casanode service..."
systemctl start casanode.service
