#!/bin/bash
set -e

echo "Removing Casanode files..."
rm -rf /opt/casanode
rm -f /etc/systemd/system/casanode.service
rm -f /etc/systemd/system/casanode-startup.service

echo "Reloading systemd..."
systemctl daemon-reload
