#!/bin/bash
set -e

if [ "$1" = "purge" ]
then
	echo "Removing Casanode files..."
	rm -rf /opt/casanode
	rm -f /etc/systemd/system/casanode.service
	rm -f /etc/systemd/system/casanode-startup.service
fi

echo "Reloading systemd..."
systemctl daemon-reload
